angular.module('Login', ['ngRoute', 'httpRequests']);
angular.module('Register', ['ngRoute', 'httpRequests']);
angular.module('Feed', ['ngRoute', 'httpRequests']);
angular.module('Profile', ['ngRoute', 'httpRequests']);
angular.module('Options', ['ngRoute', 'httpRequests']);
angular.module('Privacy', ['ngRoute', 'httpRequests']);
angular.module('Friends', ['ngRoute', 'httpRequests']);
angular.module('Logout', ['ngRoute', 'httpRequests']);
angular.module('mapApp', ['ngRoute', 'httpRequests']);