// <auto-generated />
namespace project2._4.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addAboutMe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAboutMe));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281049311_addAboutMe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
